// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nzkrqbhwxxwzivjzweat.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56a3JxYmh3eHh3eml2anp3ZWF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2OTc2MTcsImV4cCI6MjA2MjI3MzYxN30.dM0gfJI3onANjbeEFiCDmtJMg935--cVOz6vOXaaLdc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);